DROP TABLE IF EXISTS chickens;

CREATE TABLE chickens (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  firstName VARCHAR(250) NOT NULL,
  lastName VARCHAR(250) NOT NULL,
  chickenType VARCHAR(250) DEFAULT NULL
);